### ISSUE TITLE
Undefined function webform_get_conditional_sorter()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_validation#2]
`Fatal error: Call to undefined function webform_get_conditional_sorter() in /path/to/backdrop/modules/webform_validation/webform_validation.module on line 163`

(This function is available in webform for Drupal and the issue (1840776) is already flagged in the massive list of d7 commits in the webform queue: https://github.com/backdrop-contrib/webform/issues/39)

**Comment by herbdool** [comment]
@laryn I believe it's now fixed in webform 1.x-1.1.5
